export const API_URL = {
  SIGNUP_WITH_EMAIL: 'signup/admin/email',
  SIGNUP_WITH_GOOGLE: 'signup/admin/google',
  REFRESH_TOKEN: 'auth/token',
  LOGIN_WITH_EMAIL: 'auth/token',
  LOGIN_WITH_GOOGLE: 'auth/token/google',
  CONFIRM_EMAIL: 'signup/admin/confirm',
  SEND_NEW_CODE: 'signup/admin/send-new-code',
  SET_USER_NAME: 'signup/admin/username',
  SET_COMPANY_NAME: 'signup/admin/company',
  SET_TEAM: 'signup/admin/team',
  GET_TEAM_EMAILS: 'signup/admin/team/invites',
  SET_FIRST_PROJECT: 'signup/admin/project',
  REGISTRATION_DONE: 'signup/done',
  RESTORE_PASSWORD: 'users/passwords/request',
  SET_PASSWORD_INVITE: 'signup/member/email',
  SET_NEW_PASSWORD: 'users/passwords/set',
};
