export const LOCAL_STORAGE_KEYS = {
  USER: 'USER',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REGISTER_STEP: 'REGISTER_STEP',
  SIDEBAR_STATE: 'SIDEBAR_STATE',
  SIDEBAR_CURRENT_TEAM: 'SIDEBAR_CURRENT_TEAM',
};

export const OTHER = {
  AVATAR_MAX_SIZE: 10485760,
};
