/* Get teams of user */
export const FETCH_USER_DATA_REQUEST = 'user/FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'user/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = 'user/FETCH_USER_DATA_ERROR';

/* Update current user */
export const UPDATE_USER_DATA_REQUEST = 'user/UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'user/UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'user/UPDATE_USER_DATA_ERROR';
