/* Get teams of user */
export const FETCH_USER_DATA_REQUEST = 'user/FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'user/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = 'user/FETCH_USER_DATA_ERROR';

/* Update current user */
export const UPDATE_USER_DATA_REQUEST = 'user/UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'user/UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'user/UPDATE_USER_DATA_ERROR';

/* Change user's email */
export const CHANGE_USER_EMAIL_REQUEST = 'user/CHANGE_USER_EMAIL_REQUEST';
export const CHANGE_USER_EMAIL_SUCCESS = 'user/CHANGE_USER_EMAIL_SUCCESS';
export const CHANGE_USER_EMAIL_ERROR = 'user/CHANGE_USER_EMAIL_ERROR';

export const CONFIRM_NEW_USER_EMAIL_REQUEST = 'user/CONFIRM_NEW_USER_EMAIL_REQUEST';
export const CONFIRM_NEW_USER_EMAIL_SUCCESS = 'user/CONFIRM_NEW_USER_EMAIL_SUCCESS';
export const CONFIRM_NEW_USER_EMAIL_ERROR = 'user/CONFIRM_NEW_USER_EMAIL_ERROR';

export const SEND_NEW_CODE_TO_CHANGE_EMAIL_REQUEST = 'user/SEND_NEW_CODE_TO_CHANGE_EMAIL_REQUEST';
export const SEND_NEW_CODE_TO_CHANGE_EMAIL_SUCCESS = 'user/SEND_NEW_CODE_TO_CHANGE_EMAIL_SUCCESS';
export const SEND_NEW_CODE_TO_CHANGE_EMAIL_ERROR = 'user/SEND_NEW_CODE_TO_CHANGE_EMAIL_ERROR';

/* Change user's password */
export const CHANGE_USER_PASSWORD_REQUEST = 'user/CHANGE_USER_PASSWORD_REQUEST';
export const CHANGE_USER_PASSWORD_SUCCESS = 'user/CHANGE_USER_PASSWORD_SUCCESS';
export const CHANGE_USER_PASSWORD_ERROR = 'user/CHANGE_USER_PASSWORD_ERROR';

/* Change user's avatar */
export const CHANGE_USER_AVATAR_REQUEST = 'user/CHANGE_USER_AVATAR_REQUEST';
export const CHANGE_USER_AVATAR_SUCCESS = 'user/CHANGE_USER_AVATAR_SUCCESS';
export const CHANGE_USER_AVATAR_ERROR = 'user/CHANGE_USER_AVATAR_ERROR';

/* Delete user's avatar */
export const DELETE_USER_AVATAR_REQUEST = 'user/DELETE_USER_AVATAR_REQUEST';
export const DELETE_USER_AVATAR_SUCCESS = 'user/DELETE_USER_AVATAR_SUCCESS';
export const DELETE_USER_AVATAR_ERROR = 'user/DELETE_USER_AVATAR_ERROR';

/* Update user's projects */
export const UPDATE_USER_PROJECTS_REQUEST = 'user/UPDATE_USER_PROJECTS_REQUEST';
export const UPDATE_USER_PROJECTS_SUCCESS = 'user/UPDATE_USER_PROJECTS_SUCCESS';
export const UPDATE_USER_PROJECTS_ERROR = 'user/UPDATE_USER_PROJECTS_ERROR';
export const CUT_USER_PROJECT = 'user/CUT_USER_PROJECT';

/* Preloader */
export const USER_PRELOADER_START = 'user/USER_PRELOADER_START';
export const USER_PRELOADER_STOP = 'user/USER_PRELOADER_STOP';

export const AVATAR_PRELOADER_START = 'user/AVATAR_PRELOADER_START';
export const AVATAR_PRELOADER_STOP = 'user/AVATAR_PRELOADER_STOP';

/* Clear store */
export const CLEAR_USER_ERRORS = 'user/CLEAR_USER_ERRORS';
export const CLEAR_USER_EXTRA = 'user/CLEAR_USER_EXTRA';
