/* Get teams of user */
export const FETCH_USER_DATA_REQUEST = 'user/FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'user/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = 'user/FETCH_USER_DATA_ERROR';

/* Update current user */
export const UPDATE_USER_DATA_REQUEST = 'user/UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS = 'user/UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'user/UPDATE_USER_DATA_ERROR';

/* Change user's email */
export const CHANGE_USER_EMAIL_REQUEST = 'user/CHANGE_USER_EMAIL_REQUEST';
export const CHANGE_USER_EMAIL_SUCCESS = 'user/CHANGE_USER_EMAIL_SUCCESS';
export const CHANGE_USER_EMAIL_ERROR = 'user/CHANGE_USER_EMAIL_ERROR';

export const CONFIRM_NEW_USER_EMAIL_REQUEST = 'user/CONFIRM_NEW_USER_EMAIL_REQUEST';
export const CONFIRM_NEW_USER_EMAIL_SUCCESS = 'user/CONFIRM_NEW_USER_EMAIL_SUCCESS';
export const CONFIRM_NEW_USER_EMAIL_ERROR = 'user/CONFIRM_NEW_USER_EMAIL_ERROR';

/* Change user's password */
export const CHANGE_USER_PASSWORD_REQUEST = 'user/CHANGE_USER_EMAIL_REQUEST';
export const CHANGE_USER_PASSWORD_SUCCESS = 'user/CHANGE_USER_EMAIL_SUCCESS';
export const CHANGE_USER_PASSWORD_ERROR = 'user/CHANGE_USER_EMAIL_ERROR';

/* Clear store */
export const CLEAR_USER_ERRORS = 'user/CLEAR_USER_ERRORS';
