/* Socket connection */
export const SOCKET_CONNECT_REQUEST = 'socket/SOCKET_CONNECT_REQUEST';
export const SOCKET_CONNECT_SUCCESS = 'socket/SOCKET_CONNECT_SUCCESS';
export const SOCKET_CONNECT_ERROR = 'socket/SOCKET_CONNECT_ERROR';

/* Subscribe on projects */
export const SUBSCRIBE_ON_PROJECTS_REQUEST = 'socket/SUBSCRIBE_ON_PROJECTS_REQUEST';
export const SUBSCRIBE_ON_PROJECTS_SUCCESS = 'socket/SUBSCRIBE_ON_PROJECTS_SUCCESS';
export const SUBSCRIBE_ON_PROJECTS_ERROR = 'socket/SUBSCRIBE_ON_PROJECTS_ERROR';
