/* Socket connection */
export const SOCKET_CONNECT_REQUEST = 'socket/SOCKET_CONNECT_REQUEST';
export const SOCKET_CONNECT_SUCCESS = 'socket/SOCKET_CONNECT_SUCCESS';
export const SOCKET_CONNECT_ERROR = 'socket/SOCKET_CONNECT_ERROR';

/* Notification socket channel connected */
export const SOCKET_NOTIFY_CONNECTED = 'socket/SOCKET_NOTIFY_CONNECTED';

/* Subscribe on projects */
export const SUBSCRIBE_ON_NOTIFICATIONS_REQUEST = 'socket/SUBSCRIBE_ON_NOTIFICATIONS_REQUEST';
export const SUBSCRIBE_ON_NOTIFICATIONS_SUCCESS = 'socket/SUBSCRIBE_ON_NOTIFICATIONS_SUCCESS';
export const SUBSCRIBE_ON_NOTIFICATIONS_ERROR = 'socket/SUBSCRIBE_ON_NOTIFICATIONS_ERROR';
