/* Sign up with email */
export const SIGNUP_WITH_EMAIL_REQUEST = 'auth/SIGNUP_WITH_EMAIL_REQUEST';
export const SIGNUP_WITH_EMAIL_SUCCESS = 'auth/SIGNUP_WITH_EMAIL_SUCCESS';
export const SIGNUP_WITH_EMAIL_ERROR = 'auth/SIGNUP_WITH_EMAIL_ERROR';

/* Sign up with google */
export const SIGNUP_WITH_GOOGLE_REQUEST = 'auth/SIGNUP_WITH_GOOGLE_REQUEST';
export const SIGNUP_WITH_GOOGLE_SUCCESS = 'auth/SIGNUP_WITH_GOOGLE_SUCCESS';
export const SIGNUP_WITH_GOOGLE_ERROR = 'auth/SIGNUP_WITH_GOOGLE_ERROR';

/* Login in with email */
export const LOGIN_IN_WITH_EMAIL_REQUEST = 'auth/LOGIN_IN_WITH_EMAIL_REQUEST';
export const LOGIN_IN_WITH_EMAIL_SUCCESS = 'auth/LOGIN_IN_WITH_EMAIL_SUCCESS';
export const LOGIN_IN_WITH_EMAIL_ERROR = 'auth/LOGIN_IN_WITH_EMAIL_ERROR';

/* Login in with google */
export const LOGIN_IN_WITH_GOOGLE_REQUEST = 'auth/LOGIN_IN_WITH_GOOGLE_REQUES';
export const LOGIN_IN_WITH_GOOGLE_SUCCESS = 'auth/LOGIN_IN_WITH_GOOGLE_SUCCESS';
export const LOGIN_IN_WITH_GOOGLE_ERROR = 'auth/LOGIN_IN_WITH_GOOGLE_ERROR';

/* Confirm email */
export const CONFIRM_EMAIL_REQUEST = 'auth/CONFIRM_EMAIL_REQUEST';
export const CONFIRM_EMAIL_SUCCESS = 'auth/CONFIRM_EMAIL_SUCCESS';
export const CONFIRM_EMAIL_ERROR = 'auth/CONFIRM_EMAIL_ERROR';

/* Set user name */
export const SET_USER_NAME_REQUEST = 'auth/SET_USER_NAME_REQUEST';
export const SET_USER_NAME_SUCCESS = 'auth/SET_USER_NAME_SUCCESS';
export const SET_USER_NAME_ERROR = 'auth/SET_USER_NAME_ERROR';

/* Set company name */
export const SET_COMPANY_NAME_REQUEST = 'auth/SET_COMPANY_NAME_REQUEST';
export const SET_COMPANY_NAME_SUCCESS = 'auth/SET_COMPANY_NAME_SUCCESS';
export const SET_COMPANY_NAME_ERROR = 'auth/SET_COMPANY_NAME_ERROR';

/* Set company name */
export const SET_TEAM_REQUEST = 'auth/SET_TEAM_REQUEST';
export const SET_TEAM_SUCCESS = 'auth/SET_TEAM_SUCCESS';
export const SET_TEAM_ERROR = 'auth/SET_TEAM_ERROR';

/* Logout */
export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
