/* Get teams of user */
export const FETCH_USER_DATA_REQUEST = 'auth/FETCH_USER_DATA_REQUEST';
export const FETCH_USER_DATA_SUCCESS = 'auth/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = 'auth/FETCH_USER_DATA_ERROR';
