export const Default = {
  colors: {
    primaryColor: '#495570',
    secondaryColor: '#9398A2',
    buttons: {
      applyButton: {
        buttonFontBase: '#FFFFFF',
        buttonFontDisabled: '#FFFFFF',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#FFFFFF',
        base: '#53D0BA',
        disabled: '#A9E7DC',
        hoverEnabled: '#52EACF',
        activeEnabled: '#3BD1B7',
      },
      primaryColorFilledButton: {
        buttonFontBase: '#FFFFFF',
        buttonFontDisabled: '#FFFFFF',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#FFFFFF',
        base: '#495570',
        disabled: '#A4AAB7',
        hoverEnabled: '#596785',
        activeEnabled: '#3B4661',
      },
      primaryColorOutlinedButton: {
        buttonFontBase: '#495570',
        buttonFontDisabled: '#A4AAB7',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#FFFFFF',
        base: '#495570',
        disabled: '#A4AAB7',
        hoverEnabled: '#596785',
        activeEnabled: '#EBEEF4',
      },
      deleteButton: {
        buttonFontBase: '#E76A7D',
        buttonFontDisabled: '#ef9fab',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#E76A7D',
        base: '#E76A7D',
        disabled: '#ef9fab',
        hoverEnabled: '#E76A7D',
        activeEnabled: '#fae1e4',
      },
    },
    preloader: {
      default: {
        overlay: 'rgba(255, 255, 255, 0.6)',
        image: '#495570',
      },
      inverse: {
        overlay: 'rgba(73, 85, 112, 0.8)',
        image: '#d3d3d3',
      },
    },
    modal: {
      base: '#FFFFFF',
      secondary: '#F7F7F7',
      secondaryHover: '#f1f2f3',
      primaryFont: '#495570',
      secondaryFont: '#9398A2',
      border: '#D7D7D7',
    },
    input: {
      font: '#495570',
    },
    links: {},
    sidebarCheckedFont: '#FFFFFF',
    scarlet: '#E76A7D',
  },
};

export const Dark = {
  colors: {
    primaryColor: '#D3D3D3',
    secondaryColor: '#F8F8F8',
    buttons: {
      applyButton: {
        buttonFontBase: '#FFFFFF',
        buttonFontDisabled: '#FFFFFF',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#FFFFFF',
        base: '#53D0BA',
        disabled: '#A9E7DC',
        hoverEnabled: '#52EACF',
        activeEnabled: '#3BD1B7',
      },
      primaryColorFilledButton: {
        buttonFontBase: '#FFFFFF',
        buttonFontDisabled: '#FFFFFF',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#FFFFFF',
        base: '#D3D3D3',
        disabled: '#979797',
        hoverEnabled: '#c7c7c7',
        activeEnabled: '#9e9e9e',
      },
      primaryColorOutlinedButton: {
        buttonFontBase: '#FFFFFF',
        buttonFontDisabled: '#FFFFFF',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#FFFFFF',
        base: '#495570',
        disabled: '#A4AAB7',
        hoverEnabled: '#596785',
        activeEnabled: '#3B4661',
      },
      deleteButton: {
        buttonFontBase: '#E76A7D',
        buttonFontDisabled: '#ef9fab',
        buttonFontHover: '#FFFFFF',
        buttonFontActive: '#E76A7D',
        base: '#E76A7D',
        disabled: '#ef9fab',
        hoverEnabled: '#E76A7D',
        activeEnabled: '#fae1e4',
      },
    },
    preloader: {
      default: {
        overlay: 'rgba(73, 85, 112, 0.8)',
        image: '#D3D3D3',
      },
      inverse: {
        overlay: 'rgba(211, 211, 211, 0.6)',
        image: '#495570',
      },
    },
    modal: {
      base: '#495570',
      secondary: '#9398A2',
      secondaryHover: '#a3a8b2',
      primaryFont: '#FFFFFF',
      secondaryFont: '#F8F8F8',
      border: '#D3D3D3',
    },
    input: {
      font: '#FFFFFF',
    },
    sidebarCheckedFont: '#9398A2',
    scarlet: '#E76A7D',
  },
};
